version: '3.9'

services:
  db:
    image: postgres:13
    container_name: TechStoreDB
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminertask
    restart: always
    ports:
      - 8081:8081
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes:
  postgres_data: