spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/TechStoreDB
    username: yehor
    password: 1234
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
server:
  error:
    include-message: always

  #  jpa:
#    hibernate:
#      ddl-auto: none
#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/quizzical_herschel
#    username: yehor
#    password: 1423
#  jpa:
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
